version: '3.8' #yu
services:
  backend:
    build: 
      context: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://testuser:testpass@mongodb-test:27017/testdb
    depends_on:
      - mongodb-test
    command: npm run test

  mongodb-test:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass
    volumes:
      - mongo-test-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-test-data:
