version: '3'
services:
  backend:
    build: 
      context: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - frontend
  frontend:
    build: 
      context: ./web
    volumes:
      - ./web:/usr/src/app  # Mount the entire React application directory
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
