version: '3.8'  # Using a newer version for better feature support

services:
  backend:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app  # Path should be fine across OSes, but check Windows path compatibility
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - mongodb

  frontend:
    build: 
      context: ./web
    volumes:
      - ./web:/usr/src/app  # Same as for backend service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongodb-data:/data/db  # Named volume for data persistence

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongodb-data:  # Declaring the named volume
