name: Continuous Integration

on:
  push:
    branches: [main] # Triggers on a push to the main branchs
  pull_request:
    branches: [main] # Also triggers on pull requests to the main branch

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: ./web

      - name: Run Frontend Tests
        run: npm test
        working-directory: ./web

  backend-tests:
    needs: frontend-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Start Services
        run: docker-compose -f docker-compose.test.yml up -d

      - name: List Docker Containers
        run: docker ps --format "{{.Names}}"

      # - name: Run Backend Tests
      #   run: |
      #     docker exec tarsho_backend_1 sh -c "cd /usr/src/app/server && npm test"
      #   # Replace 'tarsho_backend_1' with the correct container name.

      - name: Shutdown Test Services
        run: docker-compose -f docker-compose.test.yml down

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image for Backend
        run: ./ci/build-backend.sh

      - name: Build Docker Image for Frontend
        run: ./ci/build-frontend.sh

  docker-compose-build:
    runs-on: ubuntu-latest
    needs: docker-build # Ensures Docker builds are successful before this step
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test Docker Compose Setup
        run: ./ci/build-compose.sh
