name: Continuous Integration

on:
  push:
    branches: [ main ]       # Triggers on a push to the main branchs
  pull_request:
    branches: [ main ]       # Also triggers on pull requests to the main branch

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Frontend Dependencies
      run: npm ci
      working-directory: ./web

    - name: Run Frontend Tests
      run: npm test
      working-directory: ./web

  backend-tests:
    needs: frontend-tests   # Optional: Run backend tests after frontend tests are successful
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and Run Containers with Test Configuration
      run: docker-compose -f docker-compose.test.yml up -d
    
    - name: Run Backend Tests
      run: docker exec tasho_backend_1 sh -c "npm test"
    
    - name: Shutdown Test Services
      run: docker-compose -f docker-compose.test.yml down
    
